spring:
  kafka:
    topic:
      main: library-events
      dlt: library-events.dlt
      error: library-events.error
    template:
      default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    admin:
      bootstrap-servers: localhost:9092,localhost:9093
    consumer:
      bootstrap-servers: localhost:9092,localhost:9093
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      groupId: abc1
      autoOffsetReset: earliest




server:
  port: 8081